### ISSUE TITLE
Detailed migration guide

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#64] opened 2023-09-26 12:18 UTC
Understand how to deploy the network, what do you need to run, and what parameters do you run it with:
    - Sequencer + batcher.. etc
    - Fullnodes (op-geth + op-node)
Outcome: doc / script with all the commands to run to deploy everything and correct configurations for network.

**Comment by lvpeschke** [comment] 2024-06-27 10:35
Duplicate of https://github.com/celo-org/celo-blockchain-planning/issues/276

**Closed as not planned by lvpeschke** 2024-06-27 10:35 UTC
Labels: type:documentation
