### ISSUE TITLE
Proposal for epoch rewards scheme

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/optimism#19] opened 2023-08-01 14:38 UTC
OP stack is adhering to the execution/consensus split from Ethereum after the merge with op-geth handling execution and op-node taking care of consensus.

We need to create a proposal for the epoch rewards in this new environment.

```[tasklist]
### Tasks
- [ ] design doc to more thoroughly spec out different implementation options (+ comparison to current scheme)
- [ ] decision around which design to use
- [ ] implementation plan + create tickets/next steps for continuing this work
```

**Comment by lvpeschke** [comment] 2024-07-22 15:57
Duplicate of https://github.com/celo-org/celo-blockchain-planning/issues/392.

**Closed as not planned by lvpeschke** 2024-07-22 15:57 UTC
Labels: Epic
