### ISSUE TITLE
Proposal for (epoch) rewards on execution/consensus split architecture

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#23] opened 2023-08-01 14:53 UTC
OP stack is adhering to the execution/consensus split from Ethereum after the merge with `op-geth` handling execution and `op-node` taking care of consensus.

We need to create a proposal for the epoch rewards in this new environment.

**Comment by eelanagaraj** [comment] 2023-08-16 15:13
duplicate of #19

**Closed as not planned** 2023-08-16 15:12 UTC
